app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/SpringLaba1DB?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: SpringLaba1DB
    password: D8a6TYMCVOiAHVXQ
    pool-size: 30
