spring:
  datasource:
    url: jdbc:h2:mem:springlaba5
    driverClassName: org.h2.Driver
    username: springlaba5
    password: springlaba5seniv
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
