spring:
  datasource:
    url: jdbc:h2:mem:springlaba3
    driverClassName: org.h2.Driver
    username: springlaba3
    password: springlaba3seniv
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
