app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/springlaba3db?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: springlaba3db
    password: z*bG3YOQy18nKoj]
    pool-size: 30
